/** Maps route slugs to systemRecords entityType for the shared activity panel. */
export const CRUD_ENTITY_BY_SLUG: Record<string, string> = {
  'submit-ticket': 'ticket',
  'ticket-view': 'ticket',
  'ticket-messages': 'ticket',
  'upload-documents': 'attachment',
  'reopen-ticket': 'ticket',
  feedback: 'feedback',
  'my-tickets': 'ticket',
  'assign-tickets': 'ticket',
  queues: 'ticket',
  operations: 'ticket',
  escalations: 'escalation',
  sla: 'settings',
  reassign: 'ticket',
  tickets: 'ticket',
  approvals: 'ticket',
  'sla-compliance': 'ticket',
  'respond-inquiries': 'message',
  troubleshoot: 'message',
  'update-status': 'ticket',
  'ticket-notes': 'message',
  'resolve-ticket': 'ticket',
  communicate: 'message',
  'technical-tickets': 'ticket',
  'hardware-maintenance': 'asset',
  'software-troubleshoot': 'ticket',
  'network-issues': 'ticket',
  repairs: 'repair',
  'escalate-issues': 'escalation',
  assets: 'asset',
  'monitor-requests': 'ticket',
  'track-status': 'ticket',
  'review-resolved': 'ticket',
  'create-articles': 'article',
  'edit-articles': 'article',
  faqs: 'article',
  categories: 'category',
  'publish-articles': 'article',
  'update-articles': 'article',
  reviews: 'ticket',
  'service-quality': 'ticket',
  'evaluate-performance': 'ticket',
  satisfaction: 'feedback',
  'process-improvements': 'system',
  'activity-logs': 'system',
  'user-actions': 'system',
  'ticket-audit': 'ticket',
  compliance: 'ticket',
  'audit-reports': 'system',
  'security-concerns': 'system',
  users: 'user',
  roles: 'user',
  departments: 'department',
  settings: 'settings',
  permissions: 'system',
  reports: 'system',
  performance: 'ticket',
  activity: 'system',
  'system-access': 'system',
  agents: 'user',
  'coordinate-support': 'ticket',
};

export const PAGES_WITHOUT_ACTIVITY_PANEL = new Set([
  'dashboard',
  'profile',
  'system-records',
  'knowledge-base',
  'coordinate-support',
]);
