/** Sidebar icons per menu slug (lightweight, no icon library) */
export const NAV_ICONS: Record<string, string> = {
  dashboard: '◆',
  profile: '👤',
  'system-access': '◎',
  users: '👥',
  roles: '🔐',
  permissions: '🛡',
  settings: '⚙',
  departments: '🏢',
  reports: '📊',
  activity: '📜',
  operations: '⚡',
  queues: '📥',
  'assign-tickets': '🎫',
  sla: '⏱',
  performance: '📈',
  escalations: '⬆',
  agents: '🧑‍💼',
  tickets: '🎫',
  reassign: '↔',
  'sla-compliance': '✓',
  approvals: '✅',
  'my-tickets': '📋',
  'respond-inquiries': '💬',
  troubleshoot: '🔧',
  'update-status': '🔄',
  'ticket-notes': '📝',
  'resolve-ticket': '✔',
  communicate: '📨',
  'technical-tickets': '💻',
  'hardware-maintenance': '🖥',
  'software-troubleshoot': '📀',
  'network-issues': '🌐',
  repairs: '🔩',
  'escalate-issues': '⚠',
  assets: '📦',
  'monitor-requests': '👁',
  'track-status': '📍',
  'coordinate-support': '🤝',
  'review-resolved': '✓',
  'submit-ticket': '➕',
  'ticket-view': '🔍',
  'ticket-messages': '💬',
  'upload-documents': '📎',
  'knowledge-base': '📚',
  'reopen-ticket': '↩',
  feedback: '⭐',
  'create-articles': '✏',
  'edit-articles': '📝',
  faqs: '❓',
  categories: '🏷',
  'publish-articles': '📤',
  'update-articles': '🔄',
  reviews: '🔎',
  'service-quality': '💎',
  'evaluate-performance': '📐',
  satisfaction: '😊',
  'process-improvements': '💡',
  'activity-logs': '📜',
  'user-actions': '👤',
  'ticket-audit': '🎫',
  compliance: '⚖',
  'audit-reports': '📑',
  'security-concerns': '🔒',
  'system-records': '🗂',
};

export function navIcon(slug: string): string {
  return NAV_ICONS[slug] ?? '•';
}
