import type { AppDatabase } from '@/types';
import { daysAgo, hoursAgo, hoursFromNow, isoNow } from './dates';
import { DEMO_IMAGE_PLACEHOLDER } from './files';

export function createSeedDatabase(): AppDatabase {
  const now = isoNow();
  return {
    settings: {
      siteName: 'Helpdesk Management System',
      slaEnabled: '1',
      autoAssign: '0',
      maxUploadMb: '5',
    },
    departments: [
      { id: 1, name: 'Information Technology', description: 'IT and infrastructure support' },
      { id: 2, name: 'Human Resources', description: 'HR policies and employee services' },
      { id: 3, name: 'Finance', description: 'Billing, payroll, and accounts' },
      { id: 4, name: 'Operations', description: 'General operations and facilities' },
    ],
    slaPolicies: [
      { id: 1, name: 'Standard Low', priority: 'low', responseHours: 8, resolveHours: 48, isActive: true },
      { id: 2, name: 'Standard Medium', priority: 'medium', responseHours: 4, resolveHours: 24, isActive: true },
      { id: 3, name: 'Priority High', priority: 'high', responseHours: 2, resolveHours: 12, isActive: true },
      { id: 4, name: 'Critical Urgent', priority: 'critical', responseHours: 1, resolveHours: 4, isActive: true },
    ],
    kbCategories: [
      { id: 1, name: 'Getting Started', slug: 'getting-started' },
      { id: 2, name: 'Account & Access', slug: 'account-access' },
      { id: 3, name: 'Hardware', slug: 'hardware' },
      { id: 4, name: 'Software', slug: 'software' },
      { id: 5, name: 'Network', slug: 'network' },
    ],
    users: [
      { id: 1, fullName: 'System Administrator', email: 'admin@helpdesk.local', password: 'password123', role: 'super_admin', departmentId: 1, isActive: true, createdAt: now },
      { id: 2, fullName: 'Maria Santos', email: 'manager@helpdesk.local', password: 'password123', role: 'help_desk_manager', departmentId: 1, isActive: true, createdAt: now },
      { id: 3, fullName: 'John Reyes', email: 'supervisor@helpdesk.local', password: 'password123', role: 'support_supervisor', departmentId: 1, isActive: true, createdAt: now },
      { id: 4, fullName: 'Anna Cruz', email: 'agent@helpdesk.local', password: 'password123', role: 'support_agent', departmentId: 1, isActive: true, createdAt: now },
      { id: 5, fullName: 'Mike Torres', email: 'technician@helpdesk.local', password: 'password123', role: 'it_technician', departmentId: 1, isActive: true, createdAt: now },
      { id: 6, fullName: 'Lisa Park', email: 'depthead@helpdesk.local', password: 'password123', role: 'department_head', departmentId: 2, isActive: true, createdAt: now },
      { id: 7, fullName: 'Employee User', email: 'employee@helpdesk.local', password: 'password123', role: 'employee', departmentId: 2, isActive: true, createdAt: now },
      { id: 8, fullName: 'KB Editor', email: 'kb@helpdesk.local', password: 'password123', role: 'knowledge_base_editor', departmentId: 1, isActive: true, createdAt: now },
      { id: 9, fullName: 'QA Officer', email: 'qa@helpdesk.local', password: 'password123', role: 'qa_officer', departmentId: 1, isActive: true, createdAt: now },
      { id: 10, fullName: 'System Auditor', email: 'auditor@helpdesk.local', password: 'password123', role: 'system_auditor', departmentId: 1, isActive: true, createdAt: now },
      { id: 11, fullName: 'James Wong', email: 'james.wong@helpdesk.local', password: 'password123', role: 'employee', departmentId: 3, isActive: true, createdAt: now },
      { id: 12, fullName: 'Sarah Lee', email: 'sarah.lee@helpdesk.local', password: 'password123', role: 'employee', departmentId: 4, isActive: true, createdAt: now },
      { id: 13, fullName: 'Tom Mendoza', email: 'tom.mendoza@helpdesk.local', password: 'password123', role: 'department_head', departmentId: 3, isActive: true, createdAt: now },
      { id: 14, fullName: 'Elena Rivera', email: 'elena.rivera@helpdesk.local', password: 'password123', role: 'department_head', departmentId: 4, isActive: true, createdAt: now },
      { id: 15, fullName: 'Carlos Diaz', email: 'carlos.diaz@helpdesk.local', password: 'password123', role: 'support_agent', departmentId: 1, isActive: true, createdAt: now },
    ],
    knowledgeArticles: [
      { id: 1, title: 'How to reset your password', content: 'Go to the login page and use Forgot Password.', categoryId: 2, status: 'published', authorId: 8, views: 142, createdAt: now, updatedAt: now },
      { id: 2, title: 'Printer not working', content: 'Check power and cable. Set default printer in Settings.', categoryId: 3, status: 'published', authorId: 8, views: 89, createdAt: now, updatedAt: now },
      { id: 3, title: 'VPN connection guide', content: 'Install corporate VPN client. Server: vpn.company.local', categoryId: 5, status: 'published', authorId: 8, views: 56, createdAt: now, updatedAt: now },
      { id: 4, title: 'New laptop setup checklist', content: 'Draft: imaging, antivirus, domain join...', categoryId: 3, status: 'draft', authorId: 8, views: 3, createdAt: now, updatedAt: now },
      { id: 5, title: 'Legacy payroll portal', content: 'Archived: use Finance Hub instead.', categoryId: 2, status: 'archived', authorId: 8, views: 12, createdAt: daysAgo(400), updatedAt: daysAgo(400) },
      { id: 6, title: 'FAQ: How long for ticket response?', content: 'Medium priority: 4 hours. Critical: 1 hour.', categoryId: 1, status: 'published', authorId: 8, views: 201, createdAt: now, updatedAt: now },
      { id: 7, title: 'FAQ: Can I request hardware upgrade?', content: 'Submit Hardware ticket with justification.', categoryId: 3, status: 'published', authorId: 8, views: 77, createdAt: now, updatedAt: now },
      { id: 8, title: 'Wi-Fi intermittent drops', content: 'Outdated — re-add network profile.', categoryId: 5, status: 'draft', authorId: 8, views: 5, createdAt: daysAgo(120), updatedAt: daysAgo(120) },
    ],
    tickets: [
      { id: 1, ticketCode: 'HD-1001', subject: 'Cannot access email', description: 'Outlook authentication error since morning.', category: 'Software', priority: 'high', status: 'open', requesterId: 7, assignedTo: null, departmentId: 2, slaPolicyId: 3, slaDueAt: hoursAgo(2), deptApproved: false, supervisorApproved: false, qaReviewed: false, createdAt: hoursAgo(5), updatedAt: hoursAgo(5), closedAt: null },
      { id: 2, ticketCode: 'HD-1002', subject: 'Laptop overheating', description: 'Fan loud, random shutdowns.', category: 'Hardware', priority: 'medium', status: 'assigned', requesterId: 7, assignedTo: 4, departmentId: 2, slaPolicyId: 2, slaDueAt: hoursFromNow(18), deptApproved: true, supervisorApproved: false, qaReviewed: false, createdAt: daysAgo(2), updatedAt: daysAgo(1), closedAt: null },
      { id: 3, ticketCode: 'HD-1003', subject: 'Need Adobe license', description: 'Photoshop license expired.', category: 'Software', priority: 'medium', status: 'in_progress', requesterId: 7, assignedTo: 4, departmentId: 2, slaPolicyId: 2, slaDueAt: hoursFromNow(20), deptApproved: true, supervisorApproved: false, qaReviewed: false, createdAt: daysAgo(1), updatedAt: hoursAgo(12), closedAt: null },
      { id: 4, ticketCode: 'HD-1004', subject: 'Office Wi-Fi dropping', description: 'Disconnects every 10 minutes Building B.', category: 'Network', priority: 'high', status: 'escalated', requesterId: 7, assignedTo: 5, departmentId: 2, slaPolicyId: 3, slaDueAt: hoursFromNow(8), deptApproved: true, supervisorApproved: false, qaReviewed: false, createdAt: daysAgo(3), updatedAt: daysAgo(1), closedAt: null },
      { id: 5, ticketCode: 'HD-1005', subject: 'Shared drive access denied', description: 'Cannot open HR share.', category: 'Software', priority: 'medium', status: 'resolved', requesterId: 7, assignedTo: 4, departmentId: 2, slaPolicyId: 2, slaDueAt: hoursFromNow(12), deptApproved: true, supervisorApproved: false, qaReviewed: false, createdAt: daysAgo(4), updatedAt: daysAgo(1), closedAt: null },
      { id: 6, ticketCode: 'HD-1006', subject: 'Monitor flickering', description: 'External monitor flickers on dock.', category: 'Hardware', priority: 'low', status: 'resolved', requesterId: 7, assignedTo: 4, departmentId: 2, slaPolicyId: 1, slaDueAt: hoursFromNow(40), deptApproved: true, supervisorApproved: false, qaReviewed: false, createdAt: daysAgo(5), updatedAt: daysAgo(2), closedAt: null },
      { id: 7, ticketCode: 'HD-1007', subject: 'Password reset completed', description: 'Account unlock request.', category: 'Account', priority: 'medium', status: 'closed', requesterId: 7, assignedTo: 4, departmentId: 2, slaPolicyId: 2, slaDueAt: hoursAgo(24), deptApproved: true, supervisorApproved: true, qaReviewed: true, createdAt: daysAgo(10), updatedAt: daysAgo(2), closedAt: daysAgo(2) },
      { id: 8, ticketCode: 'HD-1008', subject: 'Payroll system timeout', description: 'Payroll portal times out.', category: 'Software', priority: 'high', status: 'reopened', requesterId: 11, assignedTo: 4, departmentId: 3, slaPolicyId: 3, slaDueAt: hoursFromNow(6), deptApproved: true, supervisorApproved: false, qaReviewed: false, createdAt: daysAgo(6), updatedAt: hoursAgo(6), closedAt: null },
      { id: 9, ticketCode: 'HD-1009', subject: 'Expense report export', description: 'Cannot export Q2 PDF.', category: 'General', priority: 'low', status: 'open', requesterId: 11, assignedTo: null, departmentId: 3, slaPolicyId: 1, slaDueAt: hoursFromNow(44), deptApproved: false, supervisorApproved: false, qaReviewed: false, createdAt: hoursAgo(1), updatedAt: hoursAgo(1), closedAt: null },
      { id: 10, ticketCode: 'HD-1010', subject: 'Badge reader not working', description: 'Entrance badge reader red.', category: 'Hardware', priority: 'critical', status: 'pending_approval', requesterId: 12, assignedTo: 4, departmentId: 4, slaPolicyId: 4, slaDueAt: hoursFromNow(3), deptApproved: true, supervisorApproved: false, qaReviewed: false, createdAt: hoursAgo(8), updatedAt: hoursAgo(4), closedAt: null },
      { id: 11, ticketCode: 'HD-1011', subject: 'Server room temperature alert', description: 'HVAC 32°C in server closet.', category: 'Network', priority: 'critical', status: 'in_progress', requesterId: 12, assignedTo: 5, departmentId: 4, slaPolicyId: 4, slaDueAt: hoursFromNow(2), deptApproved: true, supervisorApproved: false, qaReviewed: false, createdAt: hoursAgo(12), updatedAt: hoursAgo(4), closedAt: null },
      { id: 12, ticketCode: 'HD-1012', subject: 'Projector in conference room', description: 'No HDMI signal Room 3A.', category: 'Hardware', priority: 'medium', status: 'closed', requesterId: 12, assignedTo: 4, departmentId: 4, slaPolicyId: 2, slaDueAt: daysAgo(2), deptApproved: true, supervisorApproved: true, qaReviewed: true, createdAt: daysAgo(14), updatedAt: daysAgo(3), closedAt: daysAgo(3) },
      { id: 13, ticketCode: 'HD-1013', subject: 'Slack notifications missing', description: 'Desktop Slack no mentions.', category: 'Software', priority: 'high', status: 'assigned', requesterId: 7, assignedTo: 15, departmentId: 2, slaPolicyId: 3, slaDueAt: hoursAgo(1), deptApproved: true, supervisorApproved: false, qaReviewed: false, createdAt: hoursAgo(6), updatedAt: hoursAgo(2), closedAt: null },
      { id: 14, ticketCode: 'HD-1014', subject: 'New hire laptop request', description: 'Start Monday — need laptop.', category: 'Hardware', priority: 'medium', status: 'open', requesterId: 11, assignedTo: null, departmentId: 3, slaPolicyId: 2, slaDueAt: hoursFromNow(22), deptApproved: true, supervisorApproved: false, qaReviewed: false, createdAt: hoursAgo(3), updatedAt: hoursAgo(3), closedAt: null },
      { id: 15, ticketCode: 'HD-1015', subject: 'Antivirus scan stuck', description: 'Scan at 99% for 6 hours.', category: 'Software', priority: 'low', status: 'in_progress', requesterId: 12, assignedTo: 15, departmentId: 4, slaPolicyId: 1, slaDueAt: hoursFromNow(36), deptApproved: true, supervisorApproved: false, qaReviewed: false, createdAt: daysAgo(2), updatedAt: hoursAgo(8), closedAt: null },
    ],
    ticketMessages: [
      { id: 1, ticketId: 2, userId: 7, message: 'Started after Windows update.', isInternal: false, createdAt: daysAgo(2) },
      { id: 2, ticketId: 2, userId: 4, message: 'Try cleaning vents with compressed air.', isInternal: false, createdAt: daysAgo(1) },
      { id: 3, ticketId: 2, userId: 4, message: 'Ordered replacement fan — ETA 2 days.', isInternal: true, createdAt: hoursAgo(20) },
      { id: 4, ticketId: 3, userId: 7, message: 'Deadline is Friday.', isInternal: false, createdAt: daysAgo(1) },
      { id: 5, ticketId: 3, userId: 4, message: 'Procurement request #PR-4421 submitted.', isInternal: false, createdAt: hoursAgo(12) },
      { id: 6, ticketId: 4, userId: 4, message: 'Escalating to network team.', isInternal: true, createdAt: daysAgo(2) },
      { id: 7, ticketId: 4, userId: 5, message: 'Surveying APs tomorrow 9 AM.', isInternal: false, createdAt: daysAgo(1) },
      { id: 8, ticketId: 7, userId: 4, message: 'Account unlocked. Change password.', isInternal: false, createdAt: daysAgo(3) },
      { id: 9, ticketId: 7, userId: 7, message: 'Confirmed working — thank you!', isInternal: false, createdAt: daysAgo(2) },
    ],
    ticketAttachments: [
      {
        id: 1,
        ticketId: 3,
        fileName: 'license_error.png',
        uploadedBy: 7,
        createdAt: daysAgo(1),
        mimeType: 'image/png',
        fileSize: 24800,
        dataUrl: DEMO_IMAGE_PLACEHOLDER,
      },
      {
        id: 2,
        ticketId: 4,
        fileName: 'wifi_screenshot.jpg',
        uploadedBy: 7,
        createdAt: daysAgo(3),
        mimeType: 'image/jpeg',
        fileSize: 31200,
        dataUrl: DEMO_IMAGE_PLACEHOLDER,
      },
      { id: 3, ticketId: 8, fileName: 'payroll_timeout.log', uploadedBy: 11, createdAt: daysAgo(5), mimeType: 'text/plain', fileSize: 4096 },
      {
        id: 4,
        ticketId: 10,
        fileName: 'badge_reader_photo.jpg',
        uploadedBy: 12,
        createdAt: hoursAgo(7),
        mimeType: 'image/jpeg',
        fileSize: 52000,
        dataUrl: DEMO_IMAGE_PLACEHOLDER,
      },
    ],
    escalations: [
      { id: 1, ticketId: 4, raisedBy: 4, targetRole: 'it_technician', reason: 'On-site AP diagnostics needed.', status: 'approved', createdAt: daysAgo(3) },
      { id: 2, ticketId: 4, raisedBy: 5, targetRole: 'help_desk_manager', reason: 'After-hours server room access.', status: 'pending', createdAt: daysAgo(1) },
      { id: 3, ticketId: 11, raisedBy: 5, targetRole: 'help_desk_manager', reason: 'Critical temperature escalation.', status: 'pending', createdAt: hoursAgo(6) },
      { id: 4, ticketId: 8, raisedBy: 4, targetRole: 'help_desk_manager', reason: 'Vendor SLA breach.', status: 'resolved', createdAt: daysAgo(4) },
    ],
    assets: [
      { id: 1, assetTag: 'LT-2024-001', name: 'Dell Latitude 5540', type: 'hardware', status: 'active', departmentId: 2, assignedUserId: 7, notes: 'Employee laptop' },
      { id: 2, assetTag: 'LT-2024-002', name: 'Dell Latitude 5540', type: 'hardware', status: 'repair', departmentId: 2, assignedUserId: 7, notes: 'HD-1002 fan repair' },
      { id: 3, assetTag: 'NET-AP-B12', name: 'Ubiquiti AP B12', type: 'network', status: 'active', departmentId: 4, assignedUserId: null, notes: 'Building B' },
      { id: 4, assetTag: 'PRT-HR-01', name: 'HP LaserJet HR', type: 'peripheral', status: 'active', departmentId: 2, assignedUserId: null, notes: 'Shared printer' },
      { id: 5, assetTag: 'SRV-RACK-01', name: 'HPE ProLiant DL380', type: 'hardware', status: 'active', departmentId: 4, assignedUserId: null, notes: 'Server room' },
    ],
    repairLogs: [
      { id: 1, assetId: 2, ticketId: 2, technicianId: 5, issueDescription: 'Fan bearing noise', resolution: 'Replaced CPU fan', status: 'completed', createdAt: daysAgo(1), completedAt: hoursAgo(6) },
      { id: 2, assetId: 3, ticketId: 4, technicianId: 5, issueDescription: 'AP disconnects', resolution: null, status: 'in_progress', createdAt: daysAgo(2), completedAt: null },
      { id: 3, assetId: 5, ticketId: 11, technicianId: 5, issueDescription: 'High temperature', resolution: 'Waiting for HVAC', status: 'open', createdAt: hoursAgo(8), completedAt: null },
    ],
    qaReviews: [
      { id: 1, ticketId: 7, reviewerId: 9, qualityScore: 5, notes: 'Excellent communication.', recommendation: 'Training example.', createdAt: daysAgo(1) },
      { id: 2, ticketId: 12, reviewerId: 9, qualityScore: 4, notes: 'Good fix.', recommendation: 'Add AV checklist to KB.', createdAt: daysAgo(2) },
    ],
    feedback: [
      { id: 1, ticketId: 7, userId: 7, rating: 5, comment: 'Anna was very helpful!', createdAt: daysAgo(2) },
      { id: 2, ticketId: 12, userId: 12, rating: 4, comment: 'Fixed same day.', createdAt: daysAgo(3) },
    ],
    notifications: [
      { id: 1, userId: 2, title: 'Pending Escalation', message: 'HD-1004 awaits approval.', link: '/help-desk-manager/escalations', isRead: false, createdAt: daysAgo(1) },
      { id: 2, userId: 2, title: 'Pending Escalation', message: 'HD-1011 critical.', link: '/help-desk-manager/escalations', isRead: false, createdAt: hoursAgo(6) },
      { id: 3, userId: 3, title: 'Closure Approval', message: 'HD-1005 ready.', link: '/support-supervisor/approvals', isRead: false, createdAt: hoursAgo(4) },
      { id: 4, userId: 3, title: 'Closure Approval', message: 'HD-1006 ready.', link: '/support-supervisor/approvals', isRead: false, createdAt: hoursAgo(2) },
      { id: 5, userId: 4, title: 'Ticket Assigned', message: 'HD-1013 assigned.', link: '/support-agent/my-tickets', isRead: false, createdAt: hoursAgo(5) },
      { id: 6, userId: 5, title: 'Technical Escalation', message: 'HD-1004 assigned.', link: '/it-technician/technical-tickets', isRead: false, createdAt: daysAgo(3) },
      { id: 7, userId: 6, title: 'Dept Approval', message: 'HD-1001 awaits approval.', link: '/department-head/approvals', isRead: false, createdAt: hoursAgo(4) },
      { id: 8, userId: 13, title: 'Dept Approval', message: 'HD-1009 awaits approval.', link: '/department-head/approvals', isRead: false, createdAt: hoursAgo(1) },
      { id: 9, userId: 9, title: 'QA Review', message: 'HD-1006 for review.', link: '/quality-assurance-officer/reviews', isRead: false, createdAt: daysAgo(1) },
      { id: 10, userId: 15, title: 'Ticket Assigned', message: 'HD-1013 & HD-1015.', link: '/support-agent/my-tickets', isRead: false, createdAt: hoursAgo(3) },
    ],
    systemRecords: [],
    auditLogs: [
      { id: 1, userId: 1, action: 'login', entityType: 'user', entityId: 1, details: 'User logged in', ipAddress: '127.0.0.1', createdAt: hoursAgo(1) },
      { id: 2, userId: 2, action: 'ticket_assign', entityType: 'ticket', entityId: 2, details: 'Assigned to Anna Cruz', ipAddress: '127.0.0.1', createdAt: daysAgo(2) },
      { id: 3, userId: 4, action: 'agent_reply', entityType: 'ticket', entityId: 3, details: 'Reply added', ipAddress: '192.168.1.10', createdAt: hoursAgo(12) },
      { id: 4, userId: 4, action: 'agent_resolve', entityType: 'ticket', entityId: 5, details: 'Marked resolved', ipAddress: '192.168.1.10', createdAt: daysAgo(1) },
      { id: 5, userId: 3, action: 'closure_approve', entityType: 'ticket', entityId: 7, details: 'Supervisor approved', ipAddress: '192.168.1.11', createdAt: daysAgo(2) },
      { id: 6, userId: 5, action: 'tech_take_ticket', entityType: 'ticket', entityId: 4, details: 'IT assigned', ipAddress: '192.168.1.20', createdAt: daysAgo(1) },
      { id: 7, userId: 6, action: 'dept_approve', entityType: 'ticket', entityId: 3, details: 'Dept approved', ipAddress: '192.168.1.30', createdAt: daysAgo(1) },
      { id: 8, userId: 7, action: 'ticket_create', entityType: 'ticket', entityId: 1, details: 'HD-1001 created', ipAddress: '192.168.1.50', createdAt: hoursAgo(5) },
      { id: 9, userId: 9, action: 'qa_review', entityType: 'ticket', entityId: 7, details: 'QA 5/5', ipAddress: '192.168.1.40', createdAt: daysAgo(1) },
      { id: 10, userId: 7, action: 'feedback_submit', entityType: 'ticket', entityId: 7, details: '5 stars', ipAddress: '192.168.1.50', createdAt: daysAgo(2) },
      { id: 11, userId: 8, action: 'kb_article_create', entityType: 'article', entityId: 6, details: 'FAQ published', ipAddress: '192.168.1.60', createdAt: daysAgo(3) },
      { id: 12, userId: 2, action: 'escalation_approved', entityType: 'escalation', entityId: 1, details: 'Approved', ipAddress: '127.0.0.1', createdAt: daysAgo(3) },
      { id: 13, userId: 9, action: 'qa_recommendation', entityType: 'system', entityId: null, details: 'Auto-close reminder after 48h.', ipAddress: '192.168.1.40', createdAt: daysAgo(5) },
    ],
    nextIds: {
      users: 16,
      tickets: 16,
      ticketMessages: 20,
      ticketAttachments: 5,
      escalations: 5,
      knowledgeArticles: 9,
      assets: 6,
      repairLogs: 4,
      qaReviews: 3,
      feedback: 3,
      notifications: 11,
      auditLogs: 20,
      systemRecords: 20,
      departments: 5,
      kbCategories: 6,
    },
  };
}
