import type { AssistantAudience } from '@/lib/ai/types';

export const QUICK_QUESTIONS: Record<AssistantAudience, string[]> = {
  guest: [
    'Ask me anything — try a fun fact!',
    'What is this helpdesk system?',
    'How do I log in with a demo role?',
    'What are all ten roles?',
    'What is the demo password?',
    'How do tickets flow from open to closed?',
    'Can I register as an employee?',
    'What is System Records?',
    'Who built this app?',
  ],
  super_admin: [
    'Ask me anything — I can help with more than tickets!',
    'What can I do as Super Admin?',
    'How do I manage users and roles?',
    'Where are departments and settings?',
    'How does System Records work?',
    'What reports should I check daily?',
    'How do permissions affect other roles?',
    'Explain the ticket lifecycle for admins',
    'What is on my profile page?',
  ],
  help_desk_manager: [
    'How do I assign tickets from the queue?',
    'What does the SLA page show?',
    'When should I escalate a ticket?',
    'How do I read performance reports?',
    'Best way to balance agent workload?',
    'What is the operations dashboard for?',
    'How do escalations get approved?',
    'Tips for morning queue triage',
  ],
  support_supervisor: [
    'How do I approve ticket closures?',
    'When should I reassign a ticket?',
    'How do I monitor agent performance?',
    'What is SLA compliance tracking?',
    'How to handle pending escalations?',
    'Difference between resolved and closed?',
    'How do I coach an agent on a ticket?',
    'What tickets need my approval today?',
  ],
  support_agent: [
    'How do I work my assigned tickets?',
    'When should I add internal notes?',
    'Steps to resolve a ticket properly',
    'How do I communicate with the requester?',
    'When to escalate to IT or supervisor?',
    'What statuses can I set on a ticket?',
    'How do I use the knowledge base while troubleshooting?',
    'What does troubleshoot page do?',
  ],
  it_technician: [
    'How do I handle technical tickets?',
    'When to log a repair vs close ticket?',
    'How does the assets module work?',
    'Network vs software ticket — who owns what?',
    'How do I escalate infrastructure issues?',
    'What goes in hardware maintenance?',
    'How are repair logs used?',
    'Critical ticket — what is the SLA?',
  ],
  department_head: [
    'How do I approve department requests?',
    'How to monitor my team’s tickets?',
    'What is track status for?',
    'When should I coordinate with support?',
    'How do I review resolved tickets?',
    'Can I see tickets from other departments?',
    'What reports matter for dept heads?',
    'How does dept approval affect SLA?',
  ],
  employee: [
    'How do I submit a new ticket?',
    'How can I track my ticket status?',
    'How do I message support on a ticket?',
    'Where is the knowledge base?',
    'How do I upload documents to a ticket?',
    'When can I reopen a closed ticket?',
    'How do I leave feedback after resolution?',
    'What priority should I choose?',
  ],
  knowledge_base_editor: [
    'How do I publish a new article?',
    'Draft vs published vs archived?',
    'How do categories organize articles?',
    'When should I update outdated articles?',
    'How do FAQs differ from articles?',
    'Best practices for KB writing',
    'How does KB reduce ticket volume?',
    'Who can see my draft articles?',
  ],
  qa_officer: [
    'What is the QA review process?',
    'How do I evaluate closed tickets?',
    'Where is customer satisfaction data?',
    'How do I score service quality?',
    'What are process improvements for?',
    'When is a ticket marked QA reviewed?',
    'How do I report quality trends?',
    'How does QA work with supervisors?',
  ],
  system_auditor: [
    'What can I audit in this system?',
    'How do activity logs differ from System Records?',
    'What is ticket audit trail?',
    'How do I check compliance?',
    'When to flag a security concern?',
    'Are audit reports read-only?',
    'What user actions are logged?',
    'How do auditors interact with tickets?',
  ],
};

export function getQuickQuestions(audience: AssistantAudience): string[] {
  return QUICK_QUESTIONS[audience] ?? QUICK_QUESTIONS.guest;
}
